# Generated by Django 5.0.3 on 2024-03-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.FileField(upload_to='media/files/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='normalized_iris_image',
            field=models.ImageField(upload_to='media/iris/'),
        ),
    ]
