# Generated by Django 5.0.3 on 2024-03-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_file_alter_user_normalized_iris_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='normalized_iris_image',
            field=models.ImageField(upload_to='iris/'),
        ),
    ]
