# Generated by Django 5.0.3 on 2024-03-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_normalized_iris_image_user_iris_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iris_image1',
            field=models.ImageField(upload_to='iris/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='iris_image2',
            field=models.ImageField(upload_to='iris/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='iris_image3',
            field=models.ImageField(upload_to='iris/'),
        ),
    ]
